services:
  # general settings
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Hyperdigital\HdReports\:
    resource: '../Classes/*'

  Hyperdigital\HdReports\Command\AvailableUpdatesPushNotificationCommand:
    tags:
      - name: console.command
        command: 'hdreports:availableUpdatesPushNotification'
        description: 'Push notification: available update'

  Hyperdigital\HdReports\Command\AvailableUpdatesEmailNotificationCommand:
    tags:
      - name: console.command
        command: 'hdreports:availableUpdatesEmailNotification'
        description: 'Email notification: available update'